# Generated by Django 2.2.16 on 2020-10-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorChoisesGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=55, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='GoldSampleGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_sample', models.IntegerField(verbose_name='Gold sample')),
            ],
        ),
        migrations.CreateModel(
            name='TypesGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=55, verbose_name='Tepe')),
            ],
        ),
        migrations.AddField(
            model_name='productprofile',
            name='color_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_id', to='checkout.ColorChoisesGuide', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='productprofile',
            name='gold_sample_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_sample_id', to='checkout.GoldSampleGuide', verbose_name='Gold sample'),
        ),
        migrations.AddField(
            model_name='productprofile',
            name='types_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types_id', to='checkout.TypesGuide', verbose_name='Type'),
        ),
    ]
